-- Generated by nwg-displays on 2026-02-19 at 19:29:51. Do not edit manually.

hl.workspace_rule({ workspace = "1" })
hl.workspace_rule({ workspace = "2" })
hl.workspace_rule({ workspace = "3" })
hl.workspace_rule({ workspace = "4" })
hl.workspace_rule({ workspace = "5" })
hl.workspace_rule({ workspace = "6" })
hl.workspace_rule({ workspace = "7" })
hl.workspace_rule({ workspace = "8" })
hl.workspace_rule({ workspace = "9" })
hl.workspace_rule({ workspace = "10" })
