standard = [
  "accessibility-inspector",
  "acpi",
  "adobe-source-code-pro-fonts",
  "alacritty",
  "amd-ucode",
  "android-tools",
  "android-udev",
  "ansible",
  "apache",
  "ark",
  "asciinema",
  "ast-grep",
  "atomicparsley",
  "atool",
  "arduino-language-server",
  "arduino-cli",
  "base",
  "base-devel",
  "bat",
  "bcachefs-tools",
  "blueman",
  "bluez-tools",
  "bluez-utils",
  "btop",
  "btrfs-progs",
  "bully",
  "cachyos-keyring",
  "cachyos-mirrorlist",
  "cachyos-v3-mirrorlist",
  "cachyos-v4-mirrorlist",
  "cdrtools",
  "celt",
  "cifs-utils",
  "clamav",
  "claude-desktop",
  "cloudflare-warp-bin",
  "cloudflared",
  "cmatrix",
  "code",
  "cowpatty",
  "cowsay",
  "cpio",
  "cronie",
  "cython",
  "dconf-editor",
  "deskflow",
  "dialog",
  "dictd",
  "discord",
  "dnsmasq",
  "docker-buildx",
  "dolphin-plugins",
  "dosfstools",
  "dotnet-sdk-8.0",
  "downgrade",
  "dpkg",
  "efibootmgr",
  "electron",
  "element-desktop",
  "evtest",
  "exfatprogs",
  "f2fs-tools",
  "faac",
  "faad2",
  "fastfetch",
  "fcitx5",
  "fcitx5-configtool",
  "fcitx5-gtk",
  "fcitx5-mozc",
  "fcitx5-qt",
  "fd",
  "ffmpegthumbnailer",
  "ffmpegthumbs",
  "figlet",
  "firefox",
  "flatpak",
  "foliate",
  "foremost",
  "fortune-mod",
  "fprintd",
  "freedownloadmanager",
  "fuse-overlayfs",
  "fzf",
  "ghostty",
  "git",
  "glib2-devel",
  "gnome-2048",
  "gnome-applets",
  "gnome-calculator",
  "gnome-calendar",
  "gnome-chess",
  "gnome-clocks",
  "gnome-disk-utility",
  "gnome-font-viewer",
  "gnome-online-accounts",
  "gnome-power-manager",
  "gnome-remote-desktop",
  "gnome-settings-daemon",
  "gnome-software",
  "gnome-tweaks",
  "gnome-weather",
  "gpart",
  "gparted",
  "grub",
  "gst-plugin-va",
  "gst-plugins-base",
  "gst-plugins-ugly",
  "gst-python",
  "gufw",
  "gum",
  "gvfs",
  "gvfs-mtp",
  "gwenview",
  "hashcat",
  "hcxdumptool",
  "hcxtools",
  "htop",
  "hyprpolkitagent",
  "intel-ucode",
  "inxi",
  "irssi",
  "jfsutils",
  "joyutils",
  "jre17-openjdk",
  "julia",
  "just",
  "kcachegrind",
  "kde-inotify-survey",
  "kdeconnect",
  "kdenetwork-filesharing",
  "kdenlive",
  "kdepim-addons",
  "kdesdk-thumbnailers",
  "kimageformats",
  "kio-admin",
  "kio-gdrive",
  "kompare",
  "konsole",
  "krdc",
  "krdp",
  "kvantum",
  "kwalletmanager",
  "lan-mouse",
  "lazygit",
  "lib32-blas",
  "lib32-freeglut",
  "lib32-lzo",
  "libc++",
  "libde265",
  "libfprint",
  "libisoburn",
  "libmp4v2",
  "libmpcdec",
  "libreoffice-fresh",
  "libtorrent",
  "libva-nvidia-driver",
  "linux",
  "linux-firmware",
  "linux-headers",
  "localsend",
  "lolcat",
  "loupe",
  "lsd",
  "luarocks",
  "lutris",
  "lxc",
  "lynx",
  "macchanger",
  "magic-wormhole",
  "mako",
  "man-db",
  "memtest86+-efi",
  "mermaid-cli",
  "metasploit",
  "micro",
  "mingw-w64-tools",
  "mokutil",
  "mono",
  "mousepad",
  "mplayer",
  "mpv-mpris",
  "mtools",
  "nano",
  "nautilus",
  "neofetch",
  "neovim",
  "net-tools",
  "network-manager-applet",
  "nikto",
  "nmap",
  "noto-fonts",
  "noto-fonts-cjk",
  "noto-fonts-emoji",
  "ntfs-3g",
  "nvidia-580xx-dkms",
  "nvidia-580xx-settings",
  "nvtop",
  "nwg-displays",
  "nwg-look",
  "obs-studio",
  "okular",
  "ollama",
  "onlyoffice-bin",
  "opencode",
  "os-prober",
  "otf-font-awesome",
  "pacman-contrib",
  "pamixer",
  "partitionmanager",
  "pear-desktop",
  "perl-image-exiftool",
  "piper",
  "pipewire-alsa",
  "plasma-browser-integration",
  "plocate",
  "power-profiles-daemon",
  "poxml",
  "pwgen",
  "python-hatchling",
  "python-installer",
  "python-pip",
  "python-pyqt6",
  "python-pyquery",
  "python-ufonormalizer",
  "python-uv",
  "python-virtualenv",
  "python-wxpython",
  "qalculate-gtk",
  "qbittorrent",
  "qemu-full",
  "qt5-quickcontrols2",
  "qt6ct",
  "rclone",
  "reaver",
  "reflector",
  "rofi",
  "rust",
  "ryujinx",
  "samba",
  "sbctl",
  "sbsigntools",
  "scdoc",
  "schroedinger",
  "scrcpy",
  "screenfetch",
  "sddm",
  "shelly",
  "shelly-cli",
  "shelly-flatpak-backend",
  "shfmt",
  "sof-firmware",
  "sox",
  "spectacle",
  "sshfs",
  "steam",
  "sunshine",
  "swaync",
  "syncthing",
  "syslinux",
  "tailscale",
  "tea",
  "termshark",
  "texlive-bin",
  "thunar",
  "thunar-archive-plugin",
  "thunar-volman",
  "thunderbird",
  "tigervnc",
  "timeshift",
  "tmux",
  "tor",
  "torbrowser-launcher",
  "tree",
  "ttf-dejavu"
  "ttf-droid",
  "ttf-fantasque-nerd",
  "ttf-fira-code",
  "ttf-jetbrains-mono",
  "tty-clock",
  "tumbler",
  "udftools",
  "uget",
  "umockdev",
  "unrar",
  "uriparser",
  "usb_modeswitch",
  "usbguard",
  "uwsm",
  "v4l2loopback-dkms",
  "veracrypt",
  "virt-manager",
  "virtualbox",
  "waybar",
  "wayvnc",
  "wgcf",
  "wifite",
  "wine",
  "winetricks",
  "xarchiver",
  "xclip",
  "xdotool",
  "xfsprogs",
  "xorg-xhost",
  "xpadneo-dkms",
  "yay",
  "yt-dlp",
  "zellij",
  "zen-browser-bin",
  "zram-generator",
  "zsh",
  "zsh-completions",
]

aur = [
]

flatpak = [
  "org.vinegarhq.Sober",
  "re.fossplant.songrec",
]
