#!/bin/bash

echo
echo -e "\e[1;31m Full Auto Update by AlvinV \e[0m"
echo
echo -e "\e[1;33m Running apt-get update \e[0m"
echo
apt-get update
echo
echo -e "\e[1;32m Finnished running apt-get update \e[0m"
echo -e "\e[1;33m Running apt update \e[0m"
echo
apt update
echo
echo -e "\e[1;32m Finnished running apt update \e[0m"
echo -e "\e[1;33m Running apt upgrade \e[0m"
echo
apt upgrade -y
echo
echo -e "\e[1;32m Finnished running apt update \e[0m"
echo -e "\e[1;33m Running apt full-upgrade \e[0m"
echo
apt-get full-upgrade -y
apt full-upgrade -y
echo
echo -e "$\e[1;32m Finnished updating all packages \e[0m"
echo
while true; do
    read -p "Do you wish to remove unused packages? [Y/N]: " yn
    case $yn in
        [Yy]* ) apt autoremove -y && apt autopurge -y; break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done